version: '3'

services:
  node:
    container_name: joys_node
    build: node
    restart: always
    entrypoint: /root/start.sh
    volumes:
      - geth_data:/root/node:rw
    ports:
      - "31323:31323"
      - "31323:31323/udp"
      - "8545:8545"
    stdin_open: true
    tty: true

volumes:
    geth_data:
      driver: local
